INSERT INTO Ulasan (id_janji_temu, rating, komentar) VALUES
(5, 5, 'Pelayanan sangat memuaskan!'),
(6, 4, 'Sangat baik, tapi ada sedikit antrian'),
(7, 3, 'Pelayanan oke, tapi perlu lebih cepat'),
(8, 5, 'Sangat direkomendasikan!'),
(9, 4, 'Rapi dan ramah, namun ruang tunggu agak penuh'),
(10, 2, 'Kurang sesuai dengan ekspektasi'),
(11, 5, 'Layanan top, tempat bersih dan nyaman'),
(12, 3, 'Hasil potongan biasa saja'),
(13, 4, 'Pelayanan cukup baik'),
(14, 5, 'Sangat memuaskan, pasti akan kembali lagi'),
(15, 4, 'Kualitas baik, sedikit mahal'),
(16, 1, 'Tidak sesuai dengan permintaan saya'),
(17, 3, 'Cukup memuaskan'),
(18, 5, 'Hasil sangat bagus, profesional!'),
(19, 4, 'Tempat nyaman, layanan oke'),
(20, 2, 'Kurang puas, hasilnya tidak rata'),
(21, 3, 'Layanan cukup memadai'),
(22, 5, 'Sangat bagus, sesuai harapan'),
(23, 4, 'Tertib dan rapi'),
(24, 5, 'Benar-benar hasil yang memuaskan'),
(25, 3, 'Harga cukup terjangkau, kualitas sesuai'),
(26, 5, 'Akan merekomendasikan ke teman-teman!'),
(27, 2, 'Hasil tidak sesuai permintaan'),
(28, 4, 'Cepat dan efisien'),
(29, 5, 'Sangat baik, hasil potongan rapi'),
(30, 3, 'Layanan biasa saja, standar'),
(31, 4, 'Memuaskan dan ramah'),
(32, 1, 'Tidak puas, pelayanan kurang ramah'),
(33, 5, 'Sangat profesional dan hasil rapi'),
(34, 3, 'Biasa saja, butuh peningkatan pelayanan');