-- Menyisipkan data ke dalam tabel Layanan
INSERT INTO Layanan (nama_layanan, deskripsi, durasi, harga) VALUES
('Haircut Basic', 'Potongan rambut dasar dengan gaya klasik', 30, 50000),
('Haircut Premium', 'Potongan rambut eksklusif dengan penataan profesional', 45, 80000),
('Haircut & Beard Trim', 'Potong rambut dan rapikan janggut', 60, 100000),
('Beard Trim', 'Rapikan dan bentuk janggut sesuai preferensi', 20, 40000),
('Full Shave', 'Cukur habis dengan teknik halus', 25, 35000),
('Shampoo & Scalp Massage', 'Pijat kulit kepala dan keramas rambut', 20, 30000),
('Hair Color', 'Pewarnaan rambut dengan pilihan warna sesuai keinginan', 60, 120000),
('Highlights', 'Highlight rambut untuk efek warna menonjol', 90, 150000),
('Keratin Treatment', 'Perawatan keratin untuk rambut lurus dan halus', 120, 200000),
('Scalp Treatment', 'Perawatan kulit kepala untuk kesehatan rambut', 45, 75000),
('Hot Towel Shave', 'Cukur dengan handuk panas untuk pengalaman nyaman', 30, 50000),
('Facial Treatment', 'Perawatan wajah untuk kesegaran dan kelembapan kulit', 40, 70000),
('Hair Wash', 'Pencucian rambut dengan sampo khusus', 15, 20000),
('Kids Haircut', 'Potongan rambut khusus anak-anak', 25, 40000),
('Senior Haircut', 'Potongan rambut khusus untuk pria senior', 30, 45000),
('Hair Spa', 'Spa rambut untuk melembapkan dan menyehatkan rambut', 60, 90000),
('Beard Coloring', 'Pewarnaan janggut sesuai warna pilihan', 30, 50000),
('Grey Blending', 'Teknik blending untuk menyamarkan uban', 45, 95000),
('Buzz Cut', 'Potongan rambut pendek sederhana', 20, 30000),
('Undercut Styling', 'Penataan rambut gaya undercut', 45, 75000),
('Pompadour Styling', 'Penataan rambut dengan gaya pompadour', 30, 60000),
('Side Part Styling', 'Penataan rambut dengan gaya belah samping', 25, 55000),
('Skin Fade', 'Potongan fade yang halus hingga kulit', 40, 70000),
('Mohawk Styling', 'Penataan rambut dengan gaya mohawk', 35, 65000),
('Flat Top Cut', 'Potongan rambut flat top', 30, 60000),
('Classic Shave', 'Cukur klasik dengan pisau cukur', 20, 30000),
('Signature Haircut', 'Potongan rambut signature dari barbershop', 50, 85000),
('Line Up', 'Penataan garis rambut dengan teknik rapi', 20, 25000),
('Eyebrow Trim', 'Rapikan alis untuk tampilan bersih', 10, 15000),
('VIP Package', 'Paket lengkap (potong rambut, pijat, dan cukur)', 90, 200000);